### ISSUE TITLE
Thanks for your sharing. I have a problem that what means for get_put_idx_value?

### ISSUE THREAD

**Issue by hellokevin96** [JarenceSJ/DeepCoNN#1]

**Comment by hellokevin96** [comment]
你好，我在运行的时候出现这个错误：embedding(): argument 'indices' (position 2) must be Tensor, not list，想请教一下

**Comment by JarenceSJ** [comment]
应该是获取词向量的那一步，输入是list，而torch的embedding要求的输入为Tensor

**Comment by hellokevin96** [comment]
嗯嗯，确实是这样的，可是我还是不太清楚如何解决，不好意思，方便留个您的联系方式吗，想问您一下

**Comment by JarenceSJ** [comment]
这是我的邮箱shuaijay@foxmail.com
